jobs:
  build:
    docker:
      - image: docker:latest
       
    steps:
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build and push Docker image
          command: |
            docker build -t vishu13/test_dash_image .
            docker login --username $vishu13 --password $dckr_pat_vRT_2eumOvMZf7zqjZBXoFUzOMo
            docker push vishu13/test_dash_image
