jobs:
  
  build:
    docker:
      - image: docker:17.05.0-ce-git
    dockerfile: Dockerfile
       
    steps:
      # ... steps for building/testing app ...
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build and push Docker image
          command: |
            docker build -t vishu13/test_dash_image .
            docker images
            docker login --username vishu13 --password dckr_pat_vRT_2eumOvMZf7zqjZBXoFUzOMo
            docker push vishu13/test_dash_image
            