version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build -t vishu13/test_dash_image .
            docker login --username $vishu13 --password $ISHUuhsi123*
            docker push vishu13/test_dash_image
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
