jobs:
  build:
    docker:
      - image: docker:latest
        auth:
          username: vishu13
          password: $ISHUuhsi123*  # context / project UI env-var reference
    steps:
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build and push Docker image
          command: |
            docker build -t vishu13/test_dash_image .
            docker login --username  --password 
            docker push vishu13/test_dash_image

